### ISSUE TITLE
Review list of shared research questions

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/iot#1]
Task: Review our list of research questions with core team, in order to kick-off the work in India. 

https://docs.google.com/document/d/1As1tlT1i-2pYrrXafBXG1j_w3GGG-geI43fGOjIhlaI/edit#heading=h.u0ru7mbb0jwe

 @simonwex @davidascher @ileddigital @thornet @autonome @secretrobotron   can you jump in this doc and edit / suggest/ comment ?

**Comment by thornet** [comment]
@LauraReynal would you like to revise this ticket to reflect the questions and process for the expert interviews & desk research in March?

**Comment by thornet** [comment]
Actually, let's start this whole repo fresh. Closing this now and we can create new tickets for the work.
