### ISSUE TITLE
Revise overarching plan for the year of IoT 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/iot#2]
Goal: we are currently preparing for India, and revising the plans. We need to do a second pass on the overarching document for 2016. 

Task: 
- have a clear picture of what is going to happen 
- have a clear budget that takes into account India + EU work

Team: @secretrobotron @thornet @ileddigital 
Then we need to submit to David and Ops for approval during Orlando

**Comment by thornet** [comment]
Completed: https://docs.google.com/document/d/1vevjU_jrwcfRar1ilcxjFnYD1XdeB5HB5Q0EGvBziEc/edit
