### ISSUE TITLE
What is the irc channel for IoT / Connected Devices?

### ISSUE THREAD

**Issue by michielbdejong** [MozillaFoundation/iot#25]
https://blog.webmaker.org/exploring-the-internet-of-things-with-mozilla says we can get in touch via irc. But through which channel?

There's `#cd-participation`, but from what I understand that channel is for meta-discussions about community participation in Mozilla's various Connected Devices pilots, right?

Is there an irc channel where we can discuss technical issues? I tried `#cd` and `#iot` but both were empty. Should we maybe use the existing `#fxos` channel for this?

**Comment by thornet** [comment]
@michielbdejong for the question! 

I created the channel #iot for now. And I'll also talk to the Connected Devices team if they're ok with sharing their channel. 

I'm @thornet on Mozilla IRC.

**Comment by brianking** [comment]
- @ensowhat

The Participation and CD Collaboration teams did a round of evaluation for new CD channels. See:

https://github.com/mozilla/participation-org/issues/321

Our conclusion was that we didn't want to create too much noise right now but would ramp up as needed.

For reference:

https://wiki.mozilla.org/Connected_Devices/Participation#Get_Connected

Happy to sync up if needed to ensure we are engaging with people in a consistent way.

**Comment by michielbdejong** [comment]
OK, guess I will use more Discourse then, instead of irc and mailing lists! :) Thanks.
