### ISSUE TITLE
Confirm list of expert interviews

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/iot#9]
Focus on the process of expert interviewing rather than # of interviews. Start with knowledgeable interviewers so we can reflect on this process. 

cc @LauraReynal

**Comment by thornet** [comment]
First round of interviews to be scheduled with: 
- Ame Elliot (Simply Secure)
- Shashank Sriram
- Dietrich Ayala

**Comment by thornet** [comment]
@thornet to do introductions, @LauraReynal to schedule chats and lead conversations.

**Comment by ileddigital** [comment]
@LauraReynal will need to use the ethical policy  (#15) when conducting the interviews. It makes things a lot easier! I'd be happy to share my experience with ethical policy practice..etc.

**Comment by thornet** [comment]
Intros for Ame, Shashank, and Dietrich.

**Comment by lauradereynal** [comment]
Thanks for the intros @thornet -- Following up now

**Comment by thornet** [comment]
Closing this ticket since 1st round of interviews determined and intro'ed.
